In [73]:
import json
import os
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed
import pandas as pd
import datetime
import streamlit as st

In [ ]:
# Constants
data_folder = "data/"
metadata_folder = "data/books_metadata/"

In [75]:
# Helper functions
def read_lines_from_file(file_path):
    """Reads lines from a file and returns them as a set"""
    if os.path.exists(file_path):
        with open(file_path, "r") as file:
            return {line.strip() for line in file if line.strip()}
    return set()

def append_line_to_file(line, file_path):
    """Appends a line such as URL or filename to a file"""
    with open(file_path, "a") as file:
        file.write(f"{line}\n")

In [ ]:
# Functions to read URL from txt file
def read_processed_urls(file_path):
    """Reads the list of processed URLs"""
    if os.path.exists(file_path):
        with open(file_path, "r") as file:
            return [line.strip() for line in file]
    return []

In [77]:
# Function to download single file
def download_file(url, folder_path):
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an error for bad status codes
        
        # Ensure folder exists
        os.makedirs(folder_path, exist_ok=True)
        filename = os.path.basename(url)  # Extract filename from URL

        # Construct the full file path
        file_path = os.path.join(folder_path, filename)

        with open(file_path, 'w') as file:
            file.write(response.text)
        print(f'{filename} downloaded successfully and saved to {folder_path}.')
    except requests.RequestException as e:
        print(f'Error downloading {url}: {e}')


# Use ThreadPoolExecutor to download files concurrently
def download_files_concurrently(urls, folder_path, max_workers=5):
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = [executor.submit(download_file, url, folder_path) for url in urls]
        for future in as_completed(futures):
            future.result()  # Wait for all futures to complete

In [78]:
# Function to process only new URLs
def process_new_urls (urls_file, processed_file, folder_path):
    """Process new URLs, skip the ones already processed"""
    # Read all URLs from the txt file
    all_urls = read_lines_from_file(urls_file)

    # Read already processed URLs
    already_processed = read_processed_urls(processed_file)
  
    # Filter out already processed URLs
    new_urls = [url for url in all_urls if url not in already_processed]

    if not new_urls:
        print("No new URLs to process.")
        return
    
    # Download the new URLs concurrently
    download_files_concurrently(new_urls, folder_path)


    # Save newly processed URLs to the processed file
    for url in new_urls:
        append_line_to_file(url, processed_file)

In [131]:
# Run code
process_new_urls(
    urls_file="data/urls.txt",
    processed_file="data/downloaded_urls.txt",
    folder_path="data/books_metadata"
)

libbyjourney-9014207-take-note.json downloaded successfully and saved to data/books_metadata.
libbyjourney-3391918-a-burst-of-light.json downloaded successfully and saved to data/books_metadata.

In [80]:
# Convert Unix timestamp
def convert_timestamp(timestamp_ms):
    timestamp_s = timestamp_ms / 1000.0
    return datetime.datetime.fromtimestamp(timestamp_s).strftime('%Y-%m-%d %H:%M:%S')

In [108]:
# Process single JSON file and return reading journey and highlights data
def process_json(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)
    
    # Extract relevant parts
    reading_journey = data.get('readingJourney', {})
    highlights = data.get('highlights', [])
    bookmarks = data.get('bookmarks', [])
    
    # Process reading journey
    titles_info = {
        "isbn": reading_journey.get("isbn", ""),
        "titleId": reading_journey.get("titleId", ""),
        "title": reading_journey.get("title", {}).get("text", ""),
        "author": reading_journey.get("author", ""),
        "publisher": reading_journey.get("publisher", ""),
        "cover_url": reading_journey.get("cover", {}).get("url", ""),
        "percent_read": reading_journey.get("percent", 0)
    }
    
    # Process highlights
    highlights_info = [
        {
            "isbn": titles_info["isbn"],
            "timestamp": convert_timestamp(highlight.get("timestamp", 0)),
            "chapter": highlight.get("chapter", ""),
            "percent": highlight.get("percent", 0),
            "color": highlight.get("color", ""),
            "quote": highlight.get("quote", ""),
            "note": highlight.get("note", "")
        }
        for highlight in highlights
    ]

     # Process bookmarks
    bookmarks_info = [
        {
            "isbn": titles_info["isbn"],
            "timestamp": convert_timestamp(bookmark.get("timestamp", 0)),
            "note": bookmark.get("note", "")
        }
        for bookmark in bookmarks
    ]
    
    return titles_info, highlights_info, bookmarks_info

In [109]:
# Process all JSON files in data folder
def process_all_json_files(folder_path, processed_log="data/processed_files.txt"):
    processed_files = read_lines_from_file(processed_log)
    all_titles = []
    all_highlights = []
    all_bookmarks = []

    # Load previously processed files
    if os.path.exists(processed_log):
        with open(processed_log, "r") as file:
            processed_files = {line.strip() for line in file}
    
    else:
        processed_files = set()
    
    # Flag to track whether new files were processed
    new_files_processed = False

    # Iterate through files in folder
    for filename in os.listdir(folder_path):
        if filename.endswith('.json') and filename not in processed_files:
            file_path = os.path.join(folder_path, filename)
            try:
                titles_info, highlights_info, bookmarks_info = process_json(file_path)
                all_titles.append(titles_info)
                all_highlights.extend(highlights_info)
                all_bookmarks.extend(bookmarks_info)

                # Record this file as processed
                with open(processed_log, "a") as file:
                    file.write(f"{filename}\n")

                # Mark that a new file has been processed
                new_files_processed = True

            except Exception as e:
                print(f"Failed to process {filename}: {e}")
    
    # Only return data if new files were processed
    if new_files_processed:
        return all_titles, all_highlights, all_bookmarks
    else:
        return None, None, None

In [110]:
def compile_data_to_dataframes(folder_path):
    all_titles, all_highlights, all_bookmarks = process_all_json_files(folder_path)
    
    # Convert lists to DataFrames
    titles_df = pd.DataFrame(all_titles)
    highlights_df = pd.DataFrame(all_highlights)
    bookmarks_df = pd.DataFrame(all_bookmarks)
    
    return titles_df, highlights_df, bookmarks_df

In [132]:
titles_df, highlights_df, bookmarks_df = compile_data_to_dataframes(metadata_folder)

In [133]:
titles_df

,isbn,titleId,title,author,publisher,cover_url,percent_read
0,9780008556167,,Take Note,Toni Tone,HarperCollins Publishers,https://img2.od-cdn.com/ImageType-100/0292-1/{...,1.000001
1,9780486824307,,A Burst of Light,Audre Lorde,Dover Publications,https://img2.od-cdn.com/ImageType-100/3082-1/{...,0.997159

In [134]:
highlights_df

,isbn,timestamp,chapter,percent,color,quote,note
0,9780486824307,2024-04-25 19:06:40,A Burst of Light: Living with Cancer,0.985796,#FFB,"I work, I love, I rest, I see and learn",
1,9780486824307,2024-04-25 19:06:40,A Burst of Light: Living with Cancer,0.985796,#FFB,Living with cancer has forced me to consciousl...,
2,9780486824307,2024-04-25 19:05:14,A Burst of Light: Living with Cancer,0.980115,#FFB,Government research grants to the National Can...,
3,9780486824307,2024-04-25 19:01:37,A Burst of Light: Living with Cancer,0.963071,#FFB,"Caring for myself is not self-indulgence, it i...",
4,9780486824307,2024-04-25 19:00:51,A Burst of Light: Living with Cancer,0.963071,#FFE0EC,I wish to live whatever life I have as fully a...,
5,9780486824307,2024-04-25 18:51:19,A Burst of Light: Living with Cancer,0.911932,#FFB,How has everyday living changed for me with th...,
6,9780486824307,2024-04-25 07:12:53,A Burst of Light: Living with Cancer,0.911932,#FFE0EC,There is an important difference between openn...,
7,9780486824307,2024-04-25 07:12:53,A Burst of Light: Living with Cancer,0.909104,#FFB,Another secret is to find some particular thin...,
8,9780486824307,2024-04-25 07:09:16,A Burst of Light: Living with Cancer,0.884627,#FFE0EC,This is no longer a time of waiting. It is a t...,
9,9780486824307,2024-04-25 07:07:45,A Burst of Light: Living with Cancer,0.880698,#DFC,I do not find it useful any longer to speculat...,Ohhh phew!
10,9780486824307,2024-04-25 07:05:06,A Burst of Light: Living with Cancer,0.863653,#FFB,"I keep observing how other people die, compari...",
11,9780486824307,2024-04-24 09:59:39,A Burst of Light: Living with Cancer,0.852284,#FFB,Battling racism and battling heterosexism and ...,
12,9780486824307,2024-04-24 09:58:26,A Burst of Light: Living with Cancer,0.846603,#FFB,I thought of the African way of perceiving lif...,
13,9780486824307,2024-04-24 09:57:18,A Burst of Light: Living with Cancer,0.840921,#FFB,In writing this I have discovered how importan...,
14,9780486824307,2024-04-24 09:55:39,A Burst of Light: Living with Cancer,0.835240,#FFB,But my worst rage was the rage at myself. For ...,
15,9780486824307,2024-04-24 09:49:51,A Burst of Light: Living with Cancer,0.801152,#FFE0EC,I much prefer to think about how I’d want to d...,
16,9780486824307,2024-04-24 09:28:34,A Burst of Light: Living with Cancer,0.801152,#FFB,Bob Marley weaving through my visualizations: ...,
17,9780486824307,2024-04-24 07:48:16,A Burst of Light: Living with Cancer,0.722240,#FFE0EC,"In the bleakest days I am kept afloat, maintai...",
18,9780486824307,2024-04-24 07:46:04,A Burst of Light: Living with Cancer,0.715925,#DFC,And of course cancer is political—look at how ...,How so?
19,9780486824307,2024-04-22 07:11:55,A Burst of Light: Living with Cancer,0.681830,#FFB,My mother always used to say that whatever you...,
20,9780486824307,2024-04-22 07:05:15,A Burst of Light: Living with Cancer,0.642060,#FFE0EC,I feel trapped on a lonely star,
21,9780486824307,2024-04-21 07:45:39,A Burst of Light: Living with Cancer,0.568196,#FFE0EC,As a living creature I am part of two kinds of...,
22,9780486824307,2024-04-20 09:38:18,A Burst of Light: Living with Cancer,0.545471,#FFE0EC,"I want to live the rest of my life, however lo...",
23,9780486824307,2024-04-19 08:30:30,A Burst of Light: Living with Cancer,0.505695,#FFB,"One hundred and fifty years ago, when the Stat...",
24,9780486824307,2024-04-19 08:21:29,A Burst of Light: Living with Cancer,0.454562,#FFB,Rather than keep yelling at white women’s gate...,
25,9780486824307,2024-04-19 08:20:17,A Burst of Light: Living with Cancer,0.448881,#FFB,When I stood up for my first reading to a pack...,
26,9780486824307,2024-04-19 08:18:13,A Burst of Light: Living with Cancer,0.437512,#FFB,’ve been reading Christa Wolf’s The Search for...,
27,9780486824307,2024-04-17 08:13:28,A Burst of Light: Living with Cancer,0.426149,#FFB,. I just know I must not surrender my body to ...,
28,9780486824307,2024-04-17 08:13:28,A Burst of Light: Living with Cancer,0.426149,#FFB,We all have to die at least once. Making that ...,
29,9780486824307,2024-04-17 08:12:16,A Burst of Light: Living with Cancer,0.420467,#FFE0EC,Mother why were we armed to fight \n\nwith clo...,
30,9780486824307,2024-04-17 08:10:22,A Burst of Light: Living with Cancer,0.402795,#FFB,"I’m certainly enjoying life in Berlin, sick or...",
31,9780486824307,2024-04-17 08:06:42,A Burst of Light: Living with Cancer,0.392061,#FFB,I suspect I shall have to concentrate upon how...,
32,9780486824307,2024-04-17 08:00:45,A Burst of Light: Living with Cancer,0.380698,#FFB,Twenty-two hours of most days I don’t believe ...,
33,9780486824307,2024-04-17 07:57:36,A Burst of Light: Living with Cancer,0.369335,#FFE0EC,Afraid is a country where they issue us passpo...,
34,9780486824307,2024-04-15 08:16:19,Turning the Beat Around: Lesbian Parenting 1986,0.312514,#FFB,it hurts to raise your children knowing they m...,
35,9780486824307,2024-04-15 08:15:06,Turning the Beat Around: Lesbian Parenting 1986,0.301151,#FFB,Like getting used to looking up instead of dow...,
36,9780486824307,2024-04-15 08:07:30,Turning the Beat Around: Lesbian Parenting 1986,0.295469,#FFB,"And if we do not grow with our children, they ...",
37,9780486824307,2024-04-15 08:05:01,Turning the Beat Around: Lesbian Parenting 1986,0.284106,#FFB,There are those who say the urge to have child...,
38,9780486824307,2024-04-15 08:03:39,Turning the Beat Around: Lesbian Parenting 1986,0.278423,#FFB,We know that all our work upon this planet is ...,
39,9780486824307,2024-04-14 09:57:14,Apartheid U.S.A.,0.250015,#FFB,Eventually institutional racism becomes a ques...,
40,9780486824307,2024-04-14 09:53:53,Apartheid U.S.A.,0.227287,#FFB,"A peaceful, licensed march to the Haitian Emba...",
41,9780486824307,2024-04-14 09:50:04,Apartheid U.S.A.,0.215924,#DFC,Because they were dirty and Black and obnoxiou...,Buddy feat A$AP Ferg?
42,9780486824307,2024-04-14 09:48:40,Apartheid U.S.A.,0.210242,#DFC,"Countless others since then—Seattle, New Orlea...","Damn, this shit HAS BEEN HAPPENING"
43,9780486824307,2024-04-14 09:44:55,Apartheid U.S.A.,0.198878,#DFC,of the most powerful country in the world,"Only Americans speak like this, swear!"
44,9780486824307,2024-04-14 09:43:49,Apartheid U.S.A.,0.193196,#FFB,Apartheid—South Africa’s Final Solution patter...,
45,9780486824307,2024-04-14 09:42:25,Apartheid U.S.A.,0.187514,#FFB,South Africa. Eighty-seven percent of the peop...,
46,9780486824307,2024-04-12 07:41:53,I Am Your Sister: Black Women Organizing Acros...,0.170469,#FFB,Just as racist stereotypes are the problem of ...,
47,9780486824307,2024-04-12 07:40:02,I Am Your Sister: Black Women Organizing Acros...,0.164787,#FFB,"How do we organize around our differences, nei...",
48,9780486824307,2024-04-12 07:38:39,I Am Your Sister: Black Women Organizing Acros...,0.159105,#FFB,Homophobia and heterosexism mean you allow you...,
49,9780486824307,2024-04-12 07:20:51,I Am Your Sister: Black Women Organizing Acros...,0.130696,#DFC,It does not mean I hate men,"For many, lesbian does mean they hate men"
50,9780486824307,2024-04-12 06:19:15,I Am Your Sister: Black Women Organizing Acros...,0.130696,#FFB,"When I say I am a Black feminist, I mean I rec...",
51,9780486824307,2024-04-12 06:17:17,I Am Your Sister: Black Women Organizing Acros...,0.125014,#FFB,I speak here about heterosexism and homophobia...,
52,9780486824307,2024-04-12 06:16:15,I Am Your Sister: Black Women Organizing Acros...,0.119332,#FFE0EC,"But, as with all families, we sometimes find i...",
53,9780486824307,2024-04-11 08:42:56,Sadomasochism: Not About Condemnation,0.096605,#DFC,You do not get people to work against what the...,Yes but what’s your answer to the question?
54,9780486824307,2024-04-11 08:42:56,Sadomasochism: Not About Condemnation,0.096605,#FFB,"In the same way that rape is not about sex, s/...",
55,9780486824307,2024-04-11 08:38:23,Sadomasochism: Not About Condemnation,0.073878,#FFB,"Erich Fromm once said, “The fact that millions...",

In [135]:
bookmarks_df

,isbn,timestamp,note
0,9780008556167,2024-04-17 18:23:51,Outgrowing friendships is a common cause of fr...
1,9780008556167,2024-04-17 08:23:50,Being nice doesn’t have to mean being agreeable
2,9780008556167,2024-04-15 18:53:35,Be honest and transparent with overthinkers in...
3,9780008556167,2024-04-15 18:49:44,Overthinking is the enemy of happiness
4,9780008556167,2024-04-15 18:33:52,Make sure your opinion of yourself holds the m...
5,9780008556167,2024-04-15 08:31:31,“You’ve changed” is only a problem if you’ve c...
6,9780486824307,2024-04-17 07:59:31,
7,9780486824307,2024-04-17 07:57:36,

In [93]:
def save_dataframes_to_csv(titles_df, highlights_df, bookmarks_df, output_dir="./dataframes"):
    """Saves the given DataFrames to CSV files in the specified directory."""
    os.makedirs(output_dir, exist_ok=True)

    try:
        titles_df.to_csv(os.path.join(output_dir, "titles_df.csv"), index=False)
        highlights_df.to_csv(os.path.join(output_dir, "highlights_df.csv"), index=False)
        bookmarks_df.to_csv(os.path.join(output_dir, "bookmarks_df.csv"), index=False)
        print("DataFrames saved successfully.")
    except Exception as e:
        print(f"Error saving DataFrames: {e}")

In [115]:
def save_dataframes_to_csv(titles_df, highlights_df, bookmarks_df, output_dir="./dataframes"):
    """Saves the given DataFrames to CSV files in the specified directory. Avoids overwriting old dataframes."""
    os.makedirs(output_dir, exist_ok=True)

    def append_and_save(df_new, filename):
        file_path = os.path.join(output_dir, filename)
        
        if os.path.exists(file_path):
            df_existing = pd.read_csv(file_path)
            combined = pd.concat([df_existing, df_new], ignore_index=True)
        else:
            combined = df_new

        # Optional: drop duplicates by primary key, e.g., "titleId" or "timestamp"
        #combined.drop_duplicates(inplace=True)

        combined.to_csv(file_path, index=False)

    try:
        append_and_save(titles_df, "titles_df.csv")
        append_and_save(highlights_df, "highlights_df.csv")
        append_and_save(bookmarks_df, "bookmarks_df.csv")
        print("DataFrames updated and saved successfully.")
    except Exception as e:
        print(f"Error saving DataFrames: {e}")